INSERT INTO  (FirstName, LastName, Bio)
VALUES 
	('Scott', 'Almes', 'Scott Almes je známý designér stolních her.'),
	('Michal','Štach','Michal Elwen Štach je spoluautorem hry Ztracený ostrov Arnak. S manželkou Mín tvoøí vysoce kreativní designérské duo.'),
	('Bruno','Cathala','Francouzský herní designér, který žije blízko Ženevy'),
	('Marco','Portugal','Brazilský herní designér. V souèasné dobì pracuje jako herní designér a vývojáø pro CMON Limited.'),
	('Alex','Olteanu','Narozen v Brazílii a v souèasné dobì pracuje jako Game Designer a Game Developer ve spoleènosti Cool Mini.'),
	('Simone','Luciani','Je známý svými složitými, støednì až støednì tìžkými eury. Získal øadu prestižních ocenìní a v souèasné dobì pracuje ve spoleènosti Cranio Creations jako vedoucí vývoje.'),
	('Dávid','Turczi','Herní designér z Maïarska. Je známý svými komplexními eury.'),
	('Reiner','Knizia','Je známý jako jeden z nejplodnìjších svìtových herních designérù'),
	('Molly','Johnson',''),
	('Robert','Melvin',''),
	('Shawn','Stankewich','V souèasnosti žije v Seattlu, kde je aktivním èlenem Playtest Northwest a designérské skupiny Seattle Board Game Designers. Shawn je spolupoøadatelem podcastu Flatout at the Table o mechanikách deskových her.'),
	('Matt','Leacock','Je herní designér, který je nejlépe známý pro tvorbu velmi populární hry Pandemic.'),
	('Ashwin','Kamath',''),
	('Clarence','Simpson',''),
	('David','Chircop','Návrháø deskových her a videoher'),
	('Kamil','Cieœla','Kamil Sanex Cieœla je herní designér a vydavatel v Awaken Realms. Tvùrce PrzyStole.org, polské stránky o hrách ameritrashes. Ve hrách miluje tìžké klima a hluboký pøíbìh.'),
	('Petr','Vojtìch','Designér z Prahy.'),
	('Michael','Kiesling','Narozen v Nìmecku. Èasto spolupracuje s herním designérem Wolfgangem Kramerem.'),
	('Wolfgang','Kramer','Je považován za jednoho z klíèových inovátorù moderních deskových her. Èasto je mu pøisuzován prùkopnický systém ovládání oblastí, jeho hra El Grande a systémy akèních bodù.'),
	('Antoine','Bauza','Je populární návrháø nìkolika ocenìných her, vèetnì 7 Wonders a Hanabi.'),
	('Corentin','Lebrat','Francouzský designér.'),
	('Frédéric','Guérard','Francouzský designér.'),
	('Benoit','Bannier','Je francouzský designér deskových her.'),
	('Keith','Meyers','Navrhl více než 3 tucty publikovaných her, vyuèuje kurzy herního designu, je autorem knihy o herním designu.Provozuje svùj vlastní spoleèenský dùm/bar/restauraci deskových her v Denveru s názvem Board Game Republic.'),
	('Robert','Dougherty',' Je herní designér, který pøispìl k sérii bodových her s miniaturami, ale i bez miniatur.'),
	('Darwin','Kastle','je designérem deckbuildingové hry Star Realms a také karetních her The Battle for Hill 218, The Battle for Sector 219 a Space Station Assault. Pracoval také na sbìratelských karetních hrách Marvel.'),
	('Paolo','Mori',''),
	('Marc','André','Jako hlavní ekonom se vìnoval pøedevším obchodu; nákup, prodej a vydìlávání penìz z akcií pro nìj byla tak trochu globální strategická hra a miloval ji. Jeho nejznámìjší hra, Splendor, byla nominována v roce 2014 ve Spiel des Jahres.'),
	('Charles','Chevallier','Je francouzský architekt a herní designér, žijící v departementu Yvelines nedaleko Paøíže.'),
	('Miranda','Evartsová',''),
	('John D.','Clair','Herní designér z Los Angeles v Kalifornii.'),
	('Sébastien','Pauchon','Švýcarský herní designér.'),
	('Jan','Vanìèek','V roce 2016 založil herní designérskou spoleènost From the Void.'),
	('Filip','Neduk',''),
	('Tomáš','Uhlíø',''),
	('Stefan','Kloß','Herní designér z Heidelbergu, Bádensko-Württembersko, Nìmecko.'),
	('Anna','Oppolzer','Herní designérka a historièka umìní z Heidelbergu. Byla vdaná za herního designéra Stefana Kloße.'),
	('Frédéric','Moyersoen','Belgický herní designér.'),
	('Michal','Peichl','Herní designér a ilustrátor z Èeské republiky, Prahy. S pár pøáteli také založil zbrusu nové vydavatelství s názvem Pink Trubadour a vyvíjejí další tituly. První z nich bude Galileo Galilei, který bude uveden v roce 2024 na Essen Spiel.'),
	('Alexandre','Emerit','Francouzský designér.'),
	('Benoit','Turpin','Navrhování her se vìnuje od roku 2013. Žije ve francouzském Toulouse.'),
	('Wim','Goossens','Zaèínající designér deskových her z Belgie. V souèasné dobì žije v Turnhoutu a pracuje pro Game Brewer.'),
	('Alexander','Pfister','Herní designér, který žije ve Vídni v Rakousku.'),
	('Henry','Audubon',''),
	('Théo','Riviére','Francouzský herní designér.'),
	('Klaus','Teuber','Nìmecký designér. Zemøel v roce 2023.'),
	('Helge','Meissner',''),
	('Kristian','Ostby','Kristian Amundsen Otsby žije poblíž Osla v Norsku. Když nenavrhuje deskové hry, pracuje jako praktický lékaø a výzkumný pracovník.'),
	('Eilif','Svensson','Norský designér.'),
	('Anna','Wermlund',''),
	('Adrian','Dinu',''),
	('Chénier','La Salle','Kanadský diplomat a herní designér.'),
	('Steve','Jackson','Americký herní designér, který založil Steve Jackson Games na poèátku 80. let.'),
	('Jeffrey','D.Allers','Rád píše o herním designu a svých zkušenostech amerického emigranta žijícího uprostøed berlínské kultury deskových her. eff je zastáncem nových herních designérù, pùsobí v poradním sboru mezinárodní asociace herních designérù (Spieleautorrenzunft nebo SAZ), jako mentor pro program Tabletop Mentorship Program a jako porotce pro Cardboard Edison Award.'),
	('Jürgen','P.Grunau','Herní designér z Nìmecka.'),
	('Peter','McPherson','Herní designér a spisovatel na volné noze z Upstate New York.'),
	('Paul','Salomon','Matematik, uèitel, otec a hráè ze St. Louis. V souèasné dobì pracuje jako vedoucí vývoje her pro Elf Creek Games a jako herní designér na volné noze pod Featherman Games LLC.'),
	('James','D´Aloisio',''),
	('Sydney','Engelstein','Spoludesignér filmu Space Cadets.'),
	('Jacob','Fryxelius','Herní vývojáø ze Švédska. Spolumajitel obchodní spoleènosti FryxGames.'),
	('Nick','Little','Pracuje jako vývojáø pro Indie Boards and Cards.'),
	('Fel','Barros','Plodný brazilský designér deskových her.'),
	('Marco','Portugalsko','Brazilský herní designér. V souèasné dobì pracuje jako herní designér a vývojáø pro CMON Limited.'),
	('Adrienne','Ezell','Má více než deset let zkušeností v grafickém designu a polygrafickém prùmyslu.'),
	('Jason','D.Kingsley','Profesionální grafik a herní designér, který žije v Texasu.'),
	('Roanna','Peroz',''),
	('John','Shulters','Grafický designér, 3D animátor, herní designér a vývojáø na volné noze.'),
	('Michael','Michaels',''),
	('Uwe','Rosenberg','Nìmecký herní designér. Proslavil se pøedevším svou karetní hrou Bohnanza, která je úspìšná jak v Nìmecku, tak na mezinárodní úrovni. Navrhl také Agricolu, hru, která sesadila Puerto Rico z trùnu jako hra s nejvyšším hodnocením na BoardGameGeek.com.'),
	('Max','J.Kobbert','Nìmecký herní designér a profesor kognitivní psychologie. Je známý pro svou sérii deskových her Labyrint.'),
	('Michael','Keller','Švýcarský hráè a herní designér.'),
	('Andreas','Odendahl','Nìmecký hráè a herní designér.'),
	('Tony','Boydell',''),
	('Štefan','Feld','Herní designér z Gengenbachu'),
	('Kevin','Hendranata','Indonéský designér deskových her.'),
	('Blazej','Kubacki','Vášnivý hráè, fanoušek kooperativních her, fantasy a procházení dungeonù, který se však nevyhýbá ani bodovým salátùm v euro stylu, a pouští se i do nebezpeèných hlubin wargamingu.'),
	('Andrej','Novac',''),
	('Adam','Kwapinski',''),
	('Paco','Yanez',''),
	('Isaias','Vallejo',''),
	('Rüdiger','Dorn','Herní designér populárních Euroher.'),
	('Petr','Mikša','Návrháø deskové hry Karak.'),
	('Alan','R.Moon','Herní designér z Anglie.'),
	('Sebastien','Pauchon','Švýcarský herní designér.'),
	('Kasper','Lapp','Herní designér z Kodanì.'),
	('Kamil','Mandell',''),
	('Andrew','Wolf','Andrew v souèasné dobì zastává pozici hlavního herního designéra v The Pokemon Company International.'),
	('Andy','Niggles','Návrháø dobyvatelské taktiky.'),
	('Donald','X.Vaccarino',''),
	('Denis','Blanchot',''),
	('Jacques','Cottereau',''),
	('Guillaume','Gille-Naves',''),
	('Igor','Polouchine','Herní designér, redaktor reklamní agentury a hudební skladatel z Francie.'),
	('Bernd','Brunnhofer','Herní designér, vydavatel her a editor her, který žije v Mnichovì. Jeho nejvìtším úspìchem jako vydavatele a editora je hra Stone Age.'),
	('Martino','Chiacchiera','Jeho hry vždy zahrnují nìco zvláštního a inovativního, jako jsou nové triky nebo standardní komponenty spárované s originální mechanikou.'),
	('Cédric','Lefebvre',''),
	('Christophe','Raimbault',''),
	('Bruno','Faidutti','Plodný francouzský herní designér, historik a sociolog, který èasto spolupracuje s dalšími herními designéry, vèetnì Alana R. Moona , Bruna Cathaly a Michaela Schachta.'),
	('Emerson','Matsuuchi',''),
	('Klaus-Jürgen','Wrede','Designér deskových her a uèitel hudby a teologie z Arnsbergu, Severní Porýní-Vestfálsko, Nìmecko a mìsta Kolína nad Rýnem. Vytvoøil populární hru Carcassonne a pomohl vytvoøit vìtšinu dalších her Carcassonne.'),
	('Grégory','Oliver',''),
	('Paul','Dennen',''),
	('Jörg','Rüden',''),
	('Petr','Štefek','')
	;