
INSERT INTO Games (Name, Description, MinPlayers, MaxPlayers, Playtime, Age, YearPublished)
VALUES
	('La Granja: Deluxe Master Set','Ve høe se 1–4 hráèi stanou mazanými majiteli farem, kteøí pìstují a dodávají zboží, rozšiøují své statky a soupeøí o vliv na místním trhu uprostøed vesnice. Po 6 kol budete rozvíjet své farmy pøidáváním polností a užiteèných vylepšení, stavìt støechy, abyste získali silné jednorázové schopnosti, najímat pomocníky, dodávat zboží øemeslníkùm a také na trh a provádìt další akce, abyste na konci hry získali nejvíce vítìzných bodù.','1','4','120','12','2023'),
	('Azul:Letohrádek','Ve tøetím samostatném pokraèování hry Azul se hráèi budou v rolích mistrù stavitelù pokoušet postavit letní altán.Každé kolo je jedna z barev „divoká“, což znamená, že mùže být použita místo jakékoliv jiné barvy. Hráèi postupnì zaplòují mozaiky ve tvaru hvìzd a získávají body. Na konci šestého kola dostanou dodateèné body podle toho, jak se jim jednotlivé hvìzdy podaøilo vyplnit barevnými dílky.','2','4','45','8','2019'),
	('Balíkáøi','Jsou rodinnou hrou, ve které se stanete doruèovateli, plánovaèi i dispeèery. Cílem hráèù je za pomoci ètyø zvolených akcí nakládat ve svém mìstì náhodnì rozmístìné balíky a odesílat je ostatním hráèùm, pøíp. rozvážet obdržené balíèky po mìstì, za což dostávají pøepravní body. Kdo má na konci pátého kola nejvíce pøepravních bodù, stává se vítìzem.','1','4','45','10','2020'),
	('Bobøí banda','Bobøí banda je jednoduchá karetní hra, která se hodí pøedevším na hraní s menšími dìtmi. Hráèi mají pøed sebou lícem dolù vyložené karty a snaží se je vymìòovat za karty s nižší hodnotou, které si buïto líznou z balíèku èi vezmou z odhazovacího balíèku. Problém je v tom, že na své karty se nemùžete podívat, takže si dìti musí poøádnì zapamatovat, aby neprohloupily. Na konci totiž vyhrává ten, kdo povymìòuje nejlépe a má nejnižší bodovou hodnotu.','2','6','20','6','2007'),
	('Bobøí klan','Je samostatnì hratelné rozšíøení karetní hry Bobøí banda. Ve høe se novì objevují bobøí hrady, ve kterých ukrýváte karty s bobry a snažíte se je chránit pøed ostatními hráèi.','2','6','20','7','2018'),
	('Bøink ve vesmíru:Velká galaktická loupež','Ve høe Bøink! Ve vesmíru se hráèi stávají zlodìji, kteøí se snaží uloupit z vesmírné lodi Tyrana Rexe co nejcennìjší poklad. Ten, kterému se podaøí naloupit poklady co nejvìtší hodnoty, se stává nejlepším zlodìjem galaxie a hru vyhrává. Jedná se o deckbuildingovou hru, která plnì vychází ze svého staršího bratøíèka Bøinku!, a jeho osvìdèené principy pøenáší do svìta sci-fi.','2','4','60','13','2017'),
	('Bubliòáci','Hra Bubliòáci je inspirována mobilními hrami typu „spoj 3“, kdy se hráèi snaží postupným skládáním rùznobarevných kulièek dosáhnout takového rozložení, aby k sobì dostali alespoò 3 stejné kulièky. Za to pak získávají body a vítìzem se stane ten, který jich bude mít na konci více.','1','2','20','8','2016'),
	('Carcassonne','Ve høe Carcassonne hráèi soutìží o získání co nejvíce bodù tím, že budují støedovìkou krajinu mìst, cest, polí a klášterù.','2','5','60','8','2001'),
	('Carcassonne: Opatství a starosta','Páté rozšíøení deskové hry Carcassonne obohacuje prùbìh hry o ètyøi nové prvky - 6 dílkù Opatství, 6 figurek Starosty, 6 figurek Povozu, 6 figurek Stodoly. Kromì toho v balení naleznete ještì 12 upravených dílkù krajiny, které se øídí dle pravidel ze základní sady.','2','6','45','8','2007'),
	('Century: Zázraky východu','Ve høe Century: Zázraky východu se plavíte se mezi poèetnými ostrovy, na kterých stavíte obchodní stanice, vylepšujete svoji loï a vymìòujete cenné zboží za jiné. Snažíte se nasbírat rùzné kombinace zboží a dovézt je do pøístavu døíve, než se to podaøí vašim soupeøùm.','2','4','50','8','2018'),
	('Citadela','V karetní høe Citadela se snažíte postavit své mìsto tak, abyste za nìj dostali co nejvíce bodù. Lepší budovy ale stojí více penìz, a tak je nutno využívat služeb rùzných postav - mordýøem lze tøeba na dané kolo odstranit jednu osobu, dìjem nìkoho okrást a opdobnì. Každé kolo mùžete tajnì zvolit jinou a jedinì správná kombinace a pøedevším odhad na to, co vzal který soupeø, vás mùže pøivést k vítìzství.','2','7','90','10','2022'),
	('Co na to Èeši: Zapeklité vztahy','Co na to Èeši: Zapeklité vztahy je týmová párty hra s jednoduchými pravidly, kterou mùžete hrát samostatnì, nebo s její pomocí rozšíøit základní hru.','3','10','45','15','2020'),
	('Colt super express','Vaši bandité jedou ve vlaku, jemuž  se postupnì odpojují vagóny. Na zaèátku každého kola si vyberou tøi ze ètyø karet - akcí, které po té postupnì odehrají. Cílem je nenechat se zastøelit a naopak odpravit ostatní bandity. Hraje se, dokud ve vlaku nezbyde jeden jediný vítìzný bandita.','3','7','15','7','2020'),
	('Disko švábi','Ve høe Disko švábi se hráèi snaží zahrát své karty tak, aby díky nim získali karty s nejnižším celkovým souètem hodnot. Toho mohou dosáhnout ziskem buïto karet s nízkými hodnotami, anebo dvojicí karet se stejnými hodnotami, které se následnì odloží.','2','6','15','8','2018'),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','',''),
	('','','','','','','')
	;
